# Generated by Django 5.2.7 on 2025-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_location_ticketrequest_remove_repairrequest_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='has_independent_value',
            field=models.BooleanField(default=True, help_text='True nếu tài sản có giá trị độc lập cần đối soát với kế toán'),
        ),
    ]
