# Generated by Django 5.2.7 on 2025-10-28 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_asset_has_independent_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('in_use', 'Đang sử dụng'), ('in_storage', 'Lưu kho'), ('liquidated', 'Thanh lý'), ('broken', 'Hư hỏng')], default='in_storage', max_length=20),
        ),
    ]
